/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_solucion (XDR *xdrs, solucion *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->respuesta))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->esCorrecto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operandos (XDR *xdrs, operandos *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->numeros, 102,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tam))
		 return FALSE;
	return TRUE;
}
