/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

void operacionSeleccionada(int opcion) {
	system("clear");
	switch (opcion) {
		case 1:
			printf("\n\t\t SUMA \n\n");
			break;
		case 2:
			printf("\n\t\t RESTA \n\n");
			break;
		case 3:
			printf("\n\t\t PRODUCTO \n\n");
			break;
		case 4:
			printf("\n\t\t DIVISION \n\n");
			break;
	}
}

void limpiarBuffer() {
	int ch;
	while ((ch = getchar()) != '\n' && ch != EOF);
}

int esNumerico(char* cadena) {
	int esCorrecto = 1;
	for(int i=0; i<(int)strlen(cadena)-1; i++) {
		if((cadena[i]<'0'||cadena[i]>'9')&&cadena[i]!='.') {
			esCorrecto = 0;
		}
	}
	return esCorrecto;
}

operandos entradaDatos() {
	char cadena[10];
	operandos operando;
	operando.tam = 0;

	while(1) {
		printf("Ingrese un valor: ");
		fgets(cadena, 99, stdin);
		if ((int)strlen(cadena) == 1) break;
		if (esNumerico(cadena)) {
			operando.numeros[operando.tam] = atof(cadena);
			operando.tam += 1;
		} else {
			printf("Es una entrada invalida.\n");
		}
	}
	return operando;
}

void calculadora_1(char *host, int opcion) {
	CLIENT *clnt;
	solucion  *resultado;
	operandos  operando;

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCULADORA, VERSION_CALCULADORA, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	limpiarBuffer();
	operando = entradaDatos();

	switch (opcion) {
		case 1:
			resultado = suma_1(&operando, clnt);
			if (resultado == (solucion *) NULL) clnt_perror (clnt, "call failed");
			break;
		case 2:
			resultado = resta_1(&operando, clnt);
			if (resultado == (solucion *) NULL) clnt_perror (clnt, "call failed");
			break;
		case 3:
			resultado = producto_1(&operando, clnt);
			if (resultado == (solucion *) NULL) clnt_perror (clnt, "call failed");
			break;
		case 4:
			resultado = division_1(&operando, clnt);
			if (resultado == (solucion *) NULL) clnt_perror (clnt, "call failed");
			break;
	}

	if (resultado->esCorrecto) {
		printf("\nResultado: %.3lf\n", resultado->respuesta);
	} else if (!resultado->esCorrecto && opcion==4) {
		printf("\nNo se puede dividir entre 0.\n");
	} else {
		printf("\nSe produjo un error en el servidor.\n");
	}

	getchar();

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}

void menuCalculadora(char *host) {
	char opcion[12];
	while(atoi(opcion) != 5) {
		system("clear");

		printf("\n\t CALCULADORA \n");
		printf("1. SUMA\n");
		printf("2. RESTA\n");
		printf("3. PRODUCTO\n");
		printf("4. DIVISION\n");
		printf("5. SALIR\n");

		printf("\nIngrese la opcion: ");
		scanf("%s", opcion);

		if (esNumerico(opcion) && atoi(opcion)>=1 && atoi(opcion)<=4) {
			operacionSeleccionada(atoi(opcion));
			calculadora_1 (host, atoi(opcion));
		}
	}
}

int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	menuCalculadora(host);

	exit (0);
}
