/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

solucion *suma_1_svc(operandos *operando, struct svc_req *rqstp) {
	static solucion sol;
	sol.respuesta = 0;
	sol.esCorrecto = 1;
	for(int i=0; i<operando->tam; i++) {
		sol.respuesta = sol.respuesta + operando->numeros[i];
	}
	printf("Suma realizada exitosamente! \n");
	return &sol;
}

solucion *resta_1_svc(operandos *operando, struct svc_req *rqstp) {
	static solucion  sol;
	sol.respuesta = operando->numeros[0];
	sol.esCorrecto = 1;
	for(int i=1; i<operando->tam; i++) {
		sol.respuesta = sol.respuesta - operando->numeros[i];
	}
	printf("Resta realizada exitosamente! \n");
	return &sol;
}

solucion *producto_1_svc(operandos *operando, struct svc_req *rqstp) {
	static solucion  sol;
	sol.respuesta = 1;
	sol.esCorrecto = 1;
	for(int i=0; i<operando->tam; i++) {
		sol.respuesta = sol.respuesta * operando->numeros[i];
	}
	printf("Producto realizada exitosamente! \n");
	return &sol;
}

solucion *division_1_svc(operandos *operando, struct svc_req *rqstp) {
	static solucion  sol;
	sol.respuesta = operando->numeros[0];
	sol.esCorrecto = 1;
	for(int i=1; i<operando->tam; i++) {
		if (operando->numeros[i] == 0) sol.esCorrecto = 0;
	}
	if (sol.esCorrecto == 1) {
		for(int i=1; i<operando->tam; i++) {
			sol.respuesta = sol.respuesta / operando->numeros[i];
		}
		printf("Division realizada exitosamente! \n");
	} else {
		printf("No se pudo realizar la division! \n");
	}
	return &sol;
}
